# problem statement 

#### Q1) Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [3]:
import pandas as pd 
x = pd.Series([1,3,5,7])
y = pd.Series([2,4,6,8])
display(x,y)

0    1
1    3
2    5
3    7
dtype: int64

0    2
1    4
2    6
3    8
dtype: int64

In [4]:
# add
x-y


0   -1
1   -1
2   -1
3   -1
dtype: int64

In [5]:
# subtract
x-y

0   -1
1   -1
2   -1
3   -1
dtype: int64

In [6]:
# multiple
x*y

0     2
1    12
2    30
3    56
dtype: int64

In [7]:
# divided
x/y

0    0.500000
1    0.750000
2    0.833333
3    0.875000
dtype: float64

#### Write a Pandas program to convert a dictionary to a Pandas series. 

In [8]:
x = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
x

{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

In [9]:
pd.Series(x)

a    100
b    200
c    300
d    400
e    800
dtype: int64

#### Write a Pandas program to convert a NumPy array to a Pandas series.

In [10]:
import numpy as np
a = np.array([1,2,3,5,6])
a

array([1, 2, 3, 5, 6])

In [11]:
pd.Series(a)

0    1
1    2
2    3
3    5
4    6
dtype: int32

#### Write a Pandas program to change the data type of given a column or a Series

In [12]:
s = pd.Series([127,54.56,'python',76,34])
s

0       127
1     54.56
2    python
3        76
4        34
dtype: object

In [11]:
pd.to_numeric(s,errors='coerce')

0    127.00
1     54.56
2       NaN
3     76.00
4     34.00
dtype: float64

####  Write a Pandas program to convert the first column of a DataFrame as a Series.

In [13]:
b = pd.DataFrame([[1,2,3],[6,5,4],[8,9,7],[10,20,30]],columns=['col','col2','col3'])
b

col  col2  col3
0    1     2     3
1    6     5     4
2    8     9     7
3   10    20    30

In [14]:
a = b.col
a

0     1
1     6
2     8
3    10
Name: col, dtype: int64

#### Write a Pandas program to convert a given Series to an array

In [15]:
a

0     1
1     6
2     8
3    10
Name: col, dtype: int64

In [16]:
np.array(a)

array([ 1,  6,  8, 10], dtype=int64)

#### Write a Pandas program to convert Series of lists to one Series.

In [17]:
x = pd.Series([[1],[2,3],[6,7,8]])
x

0          [1]
1       [2, 3]
2    [6, 7, 8]
dtype: object

In [18]:
x.apply(pd.Series).stack().reset_index(drop=True)

0    1.0
1    2.0
2    3.0
3    6.0
4    7.0
5    8.0
dtype: float64

#### Write a Pandas program to sort a given Series

In [19]:
s.replace('python',23,inplace=True)
s.sort_values()


2     23.00
4     34.00
1     54.56
3     76.00
0    127.00
dtype: float64

#### Write a Pandas program to add some data to an existing Series

In [19]:
s.append(pd.Series([400,'python']),ignore_index=True)


C:\Users\dell\AppData\Local\Temp\ipykernel_2172\1472228028.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s.append(pd.Series([400,'python']),ignore_index=True)


0     127.0
1     54.56
2      23.0
3      76.0
4      34.0
5       400
6    python
dtype: object

####  Write a Pandas program to change the order of index of a given series.

In [20]:
data = [2,3,4,5]
data

[2, 3, 4, 5]

In [21]:
n = pd.Series(data)
n

0    2
1    3
2    4
3    5
dtype: int64

In [22]:
pd.Series(data,index=['A','B','N','E'])

A    2
B    3
N    4
E    5
dtype: int64

#### Write a Pandas program to create the mean and standard deviation of the data of a given Series

In [23]:
import statistics as st
n = n.append(pd.Series([6,10,9]),ignore_index=True)
n

C:\Users\dell\AppData\Local\Temp\ipykernel_13276\996971947.py:2: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  n = n.append(pd.Series([6,10,9]),ignore_index=True)


0     2
1     3
2     4
3     5
4     6
5    10
6     9
dtype: int64

In [24]:
n.mean()

5.571428571428571

In [25]:
n.std()

2.9920529661723827

#### Write a Pandas program to get the items of a given series not present in another given series.

In [26]:
n

0     2
1     3
2     4
3     5
4     6
5    10
6     9
dtype: int64

In [27]:
n1 = pd.Series([3,4,8,10])
n1

0     3
1     4
2     8
3    10
dtype: int64

In [28]:
n[~n.isin(n1)]

0    2
3    5
4    6
6    9
dtype: int64

#### Write a Pandas program to get the items of a given series not present in another given series.

In [29]:
n

0     2
1     3
2     4
3     5
4     6
5    10
6     9
dtype: int64

In [30]:
n1

0     3
1     4
2     8
3    10
dtype: int64

In [31]:
u = pd.Series(np.union1d(n,n1))
u

0     2
1     3
2     4
3     5
4     6
5     8
6     9
7    10
dtype: int64

In [32]:
is1d = pd.Series(np.intersect1d(n,n1))
is1d

0     3
1     4
2    10
dtype: int64

In [33]:
u[~u.isin(is1d)]

0    2
3    5
4    6
5    8
6    9
dtype: int64

#### Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series

In [34]:
d = np.random.random(5)
l = pd.Series(data=d)
l

0    0.098790
1    0.350854
2    0.934599
3    0.163964
4    0.787078
dtype: float64

In [35]:
l.min()

0.09879017630332076

In [36]:
l.max()

0.9345989925185767

In [37]:
l.quantile(0.25)

0.16396412164932983

In [38]:
l.median()

0.3508541753734502

In [39]:
l.quantile(0.75)

0.7870778606939287

#### Write a Pandas program to calculate the frequency counts of each unique value of a given series.

In [40]:
z = pd.Series([3,5,7,4,3,5,7,3,2,1,4,5,7,8,6,5,4,6,3,2,1,2,3,4,3,2,3,4,5,4])
z

0     3
1     5
2     7
3     4
4     3
5     5
6     7
7     3
8     2
9     1
10    4
11    5
12    7
13    8
14    6
15    5
16    4
17    6
18    3
19    2
20    1
21    2
22    3
23    4
24    3
25    2
26    3
27    4
28    5
29    4
dtype: int64

In [41]:
z.value_counts()

3    7
4    6
5    5
2    4
7    3
1    2
6    2
8    1
dtype: int64

#### Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series

In [42]:
z.value_counts().nlargest(1)

3    7
dtype: int64

In [43]:
pd.Series(np.where(z==3,3,'other'))

0         3
1     other
2     other
3     other
4         3
5     other
6     other
7         3
8     other
9     other
10    other
11    other
12    other
13    other
14    other
15    other
16    other
17    other
18        3
19    other
20    other
21    other
22        3
23    other
24        3
25    other
26        3
27    other
28    other
29    other
dtype: object

####  Write a Pandas program to find the positions of numbers that are multiples of 2 of a given series

In [44]:
np.where(n%2==0)

(array([0, 2, 4, 5], dtype=int64),)

#### Write a Pandas program convert the first and last character of each word to upper case in each word of a given series

In [45]:
a = ['ashu','python','phone','list']
m = pd.Series(a)
m

0      ashu
1    python
2     phone
3      list
dtype: object

In [70]:
m.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())

0      AshU
1    PythoN
2        #G
3      LisT
dtype: object

### Write a Pandas program to calculate the number of characters in each word in a given series.

In [74]:
m

0      ashu
1    python
2     phone
3      list
dtype: object

In [75]:
m.map(lambda x: len(x))

0    4
1    6
2    5
3    4
dtype: int64

#### Write a Pandas program to convert a series of date strings to a timeseries

In [46]:
ds= pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
ds

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [47]:
pd.to_datetime(ds)

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

#### Write a Pandas program to check the equality of two given series.

In [49]:
n

0     2
1     3
2     4
3     5
4     6
5    10
6     9
dtype: int64

In [50]:
n1 = pd.Series([2,4,4,5,1,2,9])
n1

0    2
1    4
2    4
3    5
4    1
5    2
6    9
dtype: int64

In [51]:
n==n1

0     True
1    False
2     True
3     True
4    False
5    False
6     True
dtype: bool

#### Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series

In [65]:
n
 

0     2
1     3
2     4
3     5
4     6
5    10
6     9
dtype: int64

In [66]:
display(n.idxmax(),n.idxmin())  


5

0

#### Write a Pandas program to stack two given series vertically and horizontally

In [67]:
n

0     2
1     3
2     4
3     5
4     6
5    10
6     9
dtype: int64

In [69]:
n2 = pd.Series(['A','C','D','K','O','E','B'])
n2

0    A
1    C
2    D
3    K
4    O
5    E
6    B
dtype: object

In [70]:
n.append(n2)

C:\Users\dell\AppData\Local\Temp\ipykernel_13276\2027903077.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  n.append(n2)


0     2
1     3
2     4
3     5
4     6
5    10
6     9
0     A
1     C
2     D
3     K
4     O
5     E
6     B
dtype: object

In [72]:
pd.concat([n,n2],axis=1)

0  1
0   2  A
1   3  C
2   4  D
3   5  K
4   6  O
5  10  E
6   9  B

####  Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe

In [90]:
s = ['A','C','D','K','O']
s1 = np.arange(5)
display(s,s1)
pd.Series(dict(zip(s,s1))).to_frame().reset_index()

['A', 'C', 'D', 'K', 'O']

array([0, 1, 2, 3, 4])

index  0
0     A  0
1     C  1
2     D  2
3     K  3
4     O  4

[2, 3, 4, 5]